import { useEffect, useRef } from 'react'
import type { Conflict, Point, Robot, TempObstacle, World } from '../types'

type Props = { world: World; robots: Robot[]; conflicts: Conflict[]; obstacles: TempObstacle[]; tick: number; selected: string | null; onRobot: (robot: Robot) => void; onCell: (point: Point) => void }
const colors = { IDLE: '#68e0a0', EN_ROUTE: '#57a9ff', CONFLICT_NEGOTIATING: '#ffc857', CHARGING: '#4de1e8', EMERGENCY_STOP: '#ff5d68' }
export function GridCanvas({ world, robots, conflicts, obstacles, tick, selected, onRobot, onCell }: Props) {
  const ref = useRef<HTMLCanvasElement>(null); const view = useRef({ zoom: 1, panX: 0, panY: 0, drag: false, x: 0, y: 0 })
  useEffect(() => { const canvas = ref.current; if (!canvas) return; const parent = canvas.parentElement; if (!parent) return; const dpr = window.devicePixelRatio || 1; const width = parent.clientWidth; const height = parent.clientHeight; canvas.width = width * dpr; canvas.height = height * dpr; canvas.style.width = `${width}px`; canvas.style.height = `${height}px`; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.scale(dpr, dpr); ctx.fillStyle = '#0d151b'; ctx.fillRect(0, 0, width, height)
    const state = view.current; const cell = Math.min(width / world.width, height / world.height) * state.zoom; const ox = (width - world.width * cell) / 2 + state.panX; const oy = (height - world.height * cell) / 2 + state.panY; const at = (p: Point) => ({ x: ox + p.x * cell, y: oy + p.y * cell })
    ctx.strokeStyle = 'rgba(120, 163, 174, .13)'; ctx.lineWidth = 1; for (let x = 0; x <= world.width; x++) { ctx.beginPath(); ctx.moveTo(ox + x * cell, oy); ctx.lineTo(ox + x * cell, oy + world.height * cell); ctx.stroke() } for (let y = 0; y <= world.height; y++) { ctx.beginPath(); ctx.moveTo(ox, oy + y * cell); ctx.lineTo(ox + world.width * cell, oy + y * cell); ctx.stroke() }
    const drawCells = (items: Point[], fill: string, mark: string) => items.forEach(p => { const q = at(p); ctx.fillStyle = fill; ctx.fillRect(q.x + 2, q.y + 2, cell - 4, cell - 4); ctx.fillStyle = mark; ctx.font = `${Math.max(8, cell * .5)}px monospace`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(mark === '#' ? '#' : mark, q.x + cell / 2, q.y + cell / 2) })
    drawCells(world.static_obstacles, '#25343c', '#'); drawCells(world.charging_stations, '#123b40', '⚡'); drawCells(world.pickup_stations, '#173249', 'P'); drawCells(world.dropoff_stations, '#3b2e19', 'D')
    obstacles.forEach(o => { const q = at(o.position); const remaining = Math.max(0, o.expires_at_tick - tick); ctx.fillStyle = remaining < 10 ? 'rgba(255,93,104,.45)' : 'rgba(255,93,104,.75)'; ctx.fillRect(q.x + 1, q.y + 1, cell - 2, cell - 2); ctx.fillStyle = '#ffb3b9'; ctx.font = `${Math.max(7, cell * .28)}px monospace`; ctx.fillText(String(remaining), q.x + cell / 2, q.y + cell / 2) })
    conflicts.forEach(c => { const q = at(c.cell); ctx.strokeStyle = '#ff5d68'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(q.x + cell / 2, q.y + cell / 2, cell * .38, 0, Math.PI * 2); ctx.stroke(); ctx.beginPath(); ctx.moveTo(q.x + 4, q.y + 4); ctx.lineTo(q.x + cell - 4, q.y + cell - 4); ctx.moveTo(q.x + cell - 4, q.y + 4); ctx.lineTo(q.x + 4, q.y + cell - 4); ctx.stroke() })
    robots.forEach(r => { const q = at(r.position); const color = colors[r.state] || '#fff'; const cx = q.x + cell / 2; const cy = q.y + cell / 2; if (r.robot_id === selected || r.state === 'CONFLICT_NEGOTIATING') { ctx.strokeStyle = r.robot_id === selected ? '#fff' : color; ctx.lineWidth = r.robot_id === selected ? 2 : 1.5; ctx.beginPath(); ctx.arc(cx, cy, cell * .43, 0, Math.PI * 2); ctx.stroke() } ctx.save(); ctx.translate(cx, cy); ctx.rotate(({ NORTH: 0, EAST: Math.PI / 2, SOUTH: Math.PI, WEST: -Math.PI / 2 })[r.heading]); ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(0, -cell * .34); ctx.lineTo(cell * .27, cell * .25); ctx.lineTo(0, cell * .15); ctx.lineTo(-cell * .27, cell * .25); ctx.closePath(); ctx.fill(); ctx.restore(); ctx.fillStyle = '#dcebf0'; ctx.font = `bold ${Math.max(7, cell * .24)}px monospace`; ctx.textAlign = 'center'; ctx.fillText(r.robot_id.replace('AMR-', ''), cx, q.y + cell * .88) })
  }, [world, robots, conflicts, obstacles, tick, selected])
  const point = (event: React.MouseEvent<HTMLCanvasElement>) => { const canvas = ref.current; if (!canvas) return; const rect = canvas.getBoundingClientRect(); const state = view.current; const cell = Math.min(rect.width / world.width, rect.height / world.height) * state.zoom; const ox = (rect.width - world.width * cell) / 2 + state.panX; const oy = (rect.height - world.height * cell) / 2 + state.panY; const x = Math.floor((event.clientX - rect.left - ox) / cell); const y = Math.floor((event.clientY - rect.top - oy) / cell); if (x >= 0 && x < 30 && y >= 0 && y < 30) onCell({ x, y }) }
  return <div className="grid-shell"><div className="grid-caption"><span><i className="legend-dot" style={{ background: '#57a9ff' }} /> LIVE WAREHOUSE MAP</span><span>30 × 30 CELLS · 4-WAY NAVIGATION</span></div><canvas ref={ref} onClick={point} onWheel={e => { e.preventDefault(); view.current.zoom = Math.max(.65, Math.min(2.2, view.current.zoom + (e.deltaY > 0 ? -.08 : .08))); }} /></div>
}