import { Activity, Gauge, Timer, Zap } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api'
import { ROBOT_TYPE_COLORS, ROBOT_TYPE_LABELS } from '../state-meta'
import type { Metrics, Robot, RobotState, RobotType } from '../types'
const robotTypes: RobotType[] = ['GOODS_TO_PERSON', 'SORTING', 'SCANNING_AUDIT']
const states: RobotState[] = ['IDLE', 'EN_ROUTE_PICKUP', 'EN_ROUTE_DROPOFF', 'AUDITING', 'CHARGING', 'CONFLICT_NEGOTIATING']
export function MetricsPanel({ metrics, history, robots }: { metrics: Metrics | null; history: Array<{ tick: number; process: number; planner: number; conflicts: number; replans: number }>; robots: Robot[] }) {
  const [liveMetrics, setLiveMetrics] = useState<Metrics | null>(metrics)
  const [liveHistory, setLiveHistory] = useState(history)
  useEffect(() => { setLiveMetrics(metrics) }, [metrics])
  useEffect(() => { const refresh = () => { void api.metrics().then(next => { setLiveMetrics(next); setLiveHistory(previous => [...previous, { tick: next.total_ticks, process: next.last_tick_processing_ms, planner: next.planner_latency_ms, conflicts: next.active_conflicts, replans: next.replans }].slice(-50)) }).catch(() => undefined) }; refresh(); const timer = window.setInterval(refresh, 1500); return () => window.clearInterval(timer) }, [])
  const stateCount = (type: RobotType, state: RobotState) => robots.filter(robot => robot.robot_type === type && robot.state === state).length
  return <section className="metrics panel"><div className="panel-heading"><div><span className="eyebrow">TELEMETRY STREAM</span><h2>PERFORMANCE SIGNALS</h2></div><Activity size={15} /></div><div className="metric-cards"><div><Timer size={14} /><span>TICK PROCESS</span><strong>{liveMetrics?.last_tick_processing_ms?.toFixed(1) ?? '--'}<small> ms</small></strong></div><div><Zap size={14} /><span>PLANNER LATENCY</span><strong>{liveMetrics?.planner_latency_ms?.toFixed(1) ?? '--'}<small> ms</small></strong></div><div><Gauge size={14} /><span>ACTIVE CONFLICTS</span><strong>{liveMetrics?.active_conflicts ?? '--'}</strong></div><div><Activity size={14} /><span>REPLANS</span><strong>{liveMetrics?.replans ?? '--'}</strong></div></div><div className="composition-card"><div className="composition-heading"><span className="eyebrow">FLEET COMPOSITION</span><strong>{robots.length} AMRS</strong></div>{robotTypes.map(type => <div className="composition-row" key={type}><span className="composition-type"><i style={{ background: ROBOT_TYPE_COLORS[type] }} />{ROBOT_TYPE_LABELS[type]}</span><strong>{robots.filter(robot => robot.robot_type === type).length}</strong><small>{states.map(state => stateCount(type, state) ? `${state.replace('CONFLICT_NEGOTIATING', 'CONFLICT').replace('EN_ROUTE_PICKUP', 'PICKUP').replace('EN_ROUTE_DROPOFF', 'DROPOFF')}: ${stateCount(type, state)}` : '').filter(Boolean).join(' · ') || 'IDLE: 0'}</small></div>)}</div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={liveHistory.length ? liveHistory : history}><defs><linearGradient id="process" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#728c96" stopOpacity={.35} /><stop offset="100%" stopColor="#728c96" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="tick" hide /><YAxis hide domain={[0, 'auto']} /><Tooltip contentStyle={{ background: '#17242b', border: '1px solid #2f4a53', fontSize: 11 }} labelFormatter={value => `TICK ${value}`} /><Area type="monotone" dataKey="process" stroke="#728c96" fill="url(#process)" strokeWidth={2} /></AreaChart></ResponsiveContainer></div></section>
}