import type { RobotState, RobotType } from './types'

export const ROBOT_TYPE_COLORS: Record<RobotType, string> = {
  GOODS_TO_PERSON: '#d48645',
  SORTING: '#4f9b9a',
  SCANNING_AUDIT: '#8b9fbd',
}

export const ROBOT_TYPE_LABELS: Record<RobotType, string> = {
  GOODS_TO_PERSON: 'GOODS-TO-PERSON',
  SORTING: 'SORTING',
  SCANNING_AUDIT: 'SCANNING & AUDIT',
}

export const STATE_COLORS: Record<RobotState, string> = {
  IDLE: '#78a987',
  ASSIGNED: '#91a9b6',
  EN_ROUTE_PICKUP: '#728c96',
  PICKING: '#6d9b91',
  EN_ROUTE_DROPOFF: '#668b9a',
  DROPPING: '#b69a62',
  CONFLICT_NEGOTIATING: '#bd8154',
  AUDITING: '#8294a8',
  CHARGING: '#688b93',
  FAILSAFE_HOLD: '#b9784c',
  EMERGENCY_STOP: '#b85f58',
}

export const STATE_LABELS: Record<RobotState, string> = {
  IDLE: 'IDLE',
  ASSIGNED: 'ASSIGNED',
  EN_ROUTE_PICKUP: 'EN ROUTE',
  PICKING: 'PICKING',
  EN_ROUTE_DROPOFF: 'DROPOFF ROUTE',
  DROPPING: 'DROPPING',
  CONFLICT_NEGOTIATING: 'CONFLICT',
  AUDITING: 'AUDIT',
  CHARGING: 'CHARGING',
  FAILSAFE_HOLD: 'FAILSAFE',
  EMERGENCY_STOP: 'E-STOP',
}

export const ALL_STATES: RobotState[] = [
  'IDLE',
  'ASSIGNED',
  'EN_ROUTE_PICKUP',
  'PICKING',
  'EN_ROUTE_DROPOFF',
  'DROPPING',
  'CONFLICT_NEGOTIATING',
  'AUDITING',
  'CHARGING',
  'FAILSAFE_HOLD',
  'EMERGENCY_STOP',
]
